<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SDMSingingSkill</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net20</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>2</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup>
    <Reference Include="MonoPatcher">
      <HintPath>..\..\..\monopatcher boilerplate\MonoPatcher\bin\Debug\MonoPatcher.dll</HintPath>
    </Reference>
    <Reference Include="mscorlib">
      <HintPath>Deps\mscorlib.dll</HintPath>
      <Private>False</Private>
    </Reference>
</ItemGroup>
  <ItemGroup>
    <None Remove="UpgradeLog.htm" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Sims3GameplaySystems">
      <HintPath>Deps\Sims3GameplaySystems.dll</HintPath>
    </Reference>
    <Reference Include="SimIFace">
      <HintPath>Deps\SimIFace.dll</HintPath>
    </Reference>
    <Reference Include="UI">
      <HintPath>Deps\UI.dll</HintPath>
    </Reference>
    <Reference Include="Sims3GameplayObjects">
      <HintPath>Deps\Sims3GameplayObjects.dll</HintPath>
    </Reference>
    <Reference Include="Sims3StoreObjects">
      <HintPath>Deps\Sims3StoreObjects.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml">
    <HintPath>Deps\System.Xml.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net20" Version="1.0.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>